import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Master structure data for all programs (migrated from MasterStructure.tsx)
const MASTER_STRUCTURES: Record<string, any> = {
  "8fdc4640-719b-43a4-a398-cdaacc9cb6e0": {
    // Life-Sc
    structure: {
      total_credits: 120,
      duration: "2 years",
      contact_email: "master.lse@epfl.ch",
      website: "go.epfl.ch/master-life-sciences-engineering",
      internship_note: null,
    },
    components: [
      { name: "Master's Thesis", credits: 30, color: "hsl(var(--chart-1))" },
      { name: "Core Courses", credits: 24, color: "hsl(var(--chart-2))" },
      { name: "Options", credits: 44, color: "hsl(var(--chart-3))" },
      { name: "Scientific Thinking", credits: 4, color: "hsl(var(--chart-4))" },
      { name: "Innovation & Entrepreneurship", credits: 4, color: "hsl(var(--chart-5))" },
      { name: "SHS Requirements", credits: 6, color: "hsl(var(--muted))" },
    ],
    specializations: [
      { code: "B", name: "Biomedical Engineering", color: "bg-blue-500" },
      { code: "J", name: "Molecular & Cellular Biology", color: "bg-green-500" },
      { code: "K", name: "Computational Biology", color: "bg-purple-500" },
      { code: "L", name: "Neuroscience", color: "bg-orange-500" },
    ],
    coreCourses: [
      { name: "Basics in bioinstrumentation", credits: 4, specializations: [] },
      { name: "Bioimage informatics", credits: 4, specializations: [] },
      { name: "Biomechanics of the cardiovascular system", credits: 3, specializations: ["B"] },
      { name: "Biomechanics of the musculoskeletal system", credits: 5, specializations: ["B"] },
      { name: "Biomedical optics", credits: 3, specializations: ["B"] },
      { name: "Biophysics: physics of biological systems", credits: 4, specializations: [] },
      { name: "Biophysics: physics of the cell", credits: 3, specializations: [] },
      { name: "Biostatistics", credits: 5, specializations: ["K"] },
      { name: "Brain-like computation and intelligence", credits: 5, specializations: [] },
      { name: "Cancer biology I", credits: 5, specializations: ["J"] },
      { name: "Cellular biology and biochemistry for engineers", credits: 4, specializations: [] },
    ],
    optionCourses: [
      { name: "Computational cell biology", credits: 4, specializations: ["K"] },
      { name: "Computational motor control", credits: 4, specializations: [] },
      { name: "Computational neurosciences: neuronal dynamics", credits: 5, specializations: ["K", "L"] },
      { name: "Deep learning", credits: 4, specializations: [] },
      { name: "Deep learning in biomedicine", credits: 6, specializations: ["K"] },
      { name: "Digital epidemiology", credits: 4, specializations: ["K"] },
      { name: "Experimental biomicroscopy", credits: 4, specializations: ["B", "J", "L"] },
      { name: "Fundamentals of biomedical imaging", credits: 4, specializations: ["B"] },
      { name: "Image analysis and pattern recognition", credits: 4, specializations: [] },
      { name: "Immunoengineering", credits: 4, specializations: ["J"] },
      { name: "Lab immersion I", credits: 8, specializations: ["B", "J", "K", "L"] },
      { name: "Neural signals and signal processing", credits: 6, specializations: ["L"] },
      { name: "Neuroscience", credits: 4, specializations: ["L"] },
      { name: "Single cell biology", credits: 4, specializations: ["J", "K", "L"] },
      { name: "Stem cells and organoids", credits: 3, specializations: ["B", "J"] },
      { name: "Synthetic biology", credits: 4, specializations: ["L"] },
    ],
    innovationCourses: [
      { name: "Concept to early-stage drug and medtech products", credits: 4 },
      { name: "Entrepreneurship in food and nutrition science", credits: 4 },
      { name: "Entrepreneurship in life sciences", credits: 4 },
      { name: "Strategic management of innovation", credits: 4 },
    ],
    minors: [],
  },
  "f48170bd-53f9-4774-81e7-7759355a3f0a": {
    // AR (Architecture)
    structure: {
      total_credits: 120,
      duration: "2 years",
      contact_email: "master.architecture@epfl.ch",
      website: "go.epfl.ch/master-architecture",
      internship_note: null,
    },
    components: [
      { name: "Master's Thesis", credits: 30, color: "hsl(var(--chart-1))" },
      { name: "Core Courses", credits: 24, color: "hsl(var(--chart-2))" },
      { name: "Options", credits: 27, color: "hsl(var(--chart-3))" },
      { name: "Superstudio", credits: 24, color: "hsl(var(--chart-4))" },
      { name: "SHS Requirements", credits: 15, color: "hsl(var(--chart-5))" },
    ],
    specializations: [
      { code: "A", name: "Design", color: "bg-red-500" },
      { code: "B", name: "Habitat", color: "bg-blue-500" },
      { code: "C", name: "Territory", color: "bg-green-500" },
      { code: "D", name: "Rehabilitation", color: "bg-yellow-500" },
      { code: "E", name: "Sustainability", color: "bg-purple-500" },
    ],
    coreCourses: [
      { name: "Énoncé théorique de master", credits: 12, specializations: [] },
      { name: "Superstudio A", credits: 12, specializations: [] },
      { name: "The origins of domestic space", credits: 3, specializations: ["A", "B", "C", "D", "E"] },
      { name: "Visions et stratégies", credits: 6, specializations: [] },
      { name: "Architecture and monasticism", credits: 3, specializations: [] },
      { name: "Data centers: architecture, environment, information", credits: 3, specializations: ["E"] },
      { name: "Exquisite corpse: Architecture assembled", credits: 3, specializations: ["C"] },
      { name: "Political economy of design", credits: 3, specializations: [] },
      { name: "Reading the Renaissance", credits: 3, specializations: [] },
    ],
    optionCourses: [
      { name: "UE C: Habitat et société", credits: 4, specializations: ["B", "E"] },
      { name: "UE D: Territoire et société", credits: 4, specializations: ["B"] },
      { name: "UE F: Architecture et réhabilitation", credits: 4, specializations: ["D"] },
      { name: "UE H: Graphie", credits: 4, specializations: [] },
      { name: "UE J: Territoire et paysage", credits: 4, specializations: ["C"] },
      { name: "UE K: Architecture et durabilité : études de performances", credits: 4, specializations: ["C", "D"] },
      { name: "UE N: Constructing the view", credits: 4, specializations: ["A", "C", "E"] },
      { name: "UE R: Introduction au BIM (Building Information Modeling)", credits: 4, specializations: [] },
      { name: "UE S: Foundations, basements, and the underground", credits: 4, specializations: ["D"] },
      { name: "UE U: Cartography", credits: 4, specializations: ["B", "C"] },
      { name: "UE V: Visions et utopies", credits: 4, specializations: ["E"] },
      { name: "UE X: Experience design", credits: 4, specializations: ["A"] },
      { name: "Architectural anthropology", credits: 3, specializations: [] },
      { name: "Architecture et énergie solaire", credits: 4, specializations: [] },
      { name: "Architecture merveilleuse", credits: 3, specializations: ["E"] },
      { name: "Behind/Beyond future cities", credits: 3, specializations: [] },
      { name: "Building design in the circular economy", credits: 3, specializations: ["D"] },
      { name: "Climate and water sensitive urban design", credits: 4, specializations: [] },
      { name: "Comfort and architecture: sustainable strategies", credits: 3, specializations: ["D"] },
      { name: "Construction policy", credits: 3, specializations: [] },
      { name: "Digital design and making: a critical introduction", credits: 3, specializations: ["A"] },
      { name: "Économie du sol et de l'immobilier", credits: 3, specializations: ["B"] },
      { name: "Économie spatiale et régionale", credits: 3, specializations: ["C"] },
      { name: "Green spaces – concepts and planning approaches", credits: 4, specializations: [] },
      { name: "Habitat et développement urbain", credits: 3, specializations: ["B", "C"] },
      { name: "Habitat et typologie", credits: 3, specializations: ["B", "E"] },
    ],
    minors: [],
  },
  "4e746be0-7627-48f0-b1dd-7758040860a5": {
    // CIV (Civil Engineering)
    structure: {
      total_credits: 120,
      duration: "2 years",
      contact_email: "secretariat.sgc@epfl.ch",
      website: "go.epfl.ch/master-civil-engineering",
      internship_note: null,
    },
    components: [
      { name: "Master's Thesis", credits: 30, color: "hsl(var(--chart-1))" },
      { name: "Options", credits: 60, color: "hsl(var(--chart-2))" },
      { name: "Transversal Courses", credits: 14, color: "hsl(var(--chart-3))" },
      { name: "Projects & Lab", credits: 16, color: "hsl(var(--chart-4))" },
    ],
    specializations: [
      { code: "B", name: "Geotechnics", color: "bg-amber-600" },
      { code: "C", name: "Transport and Mobility", color: "bg-blue-500" },
      { code: "D", name: "Structural Engineering", color: "bg-red-500" },
      { code: "E", name: "Hydraulics", color: "bg-cyan-500" },
      { code: "F", name: "Urban Energy", color: "bg-green-500" },
    ],
    coreCourses: [],
    transversalCourses: [
      { name: "Analyse et gestion de risques", credits: 2, specializations: [] },
      { name: "Computational systems thinking for sustainable eng.", credits: 4, specializations: [] },
      { name: "Contrats de construction et responsabilité", credits: 3, specializations: [] },
      { name: "Droit public pour ingénieur·es civil·es", credits: 2, specializations: [] },
      { name: "Etudes d'impact sur l'environnement", credits: 3, specializations: [] },
      { name: "Innovation for construction and the environment", credits: 3, specializations: [] },
      { name: "Intercultural presentation skills", credits: 2, specializations: [] },
      { name: "Management de projet et analyse de risque", credits: 4, specializations: [] },
      { name: "Programming concept in scientific computing", credits: 4, specializations: [] },
      { name: "Research skills for engineers", credits: 2, specializations: [] },
    ],
    optionCourses: [
      { name: "Advanced composites in engineering structures", credits: 3, specializations: ["D"] },
      { name: "Bridge design", credits: 3, specializations: [] },
      { name: "Composites design and innovation", credits: 3, specializations: [] },
      { name: "Computational geomechanics", credits: 4, specializations: ["B"] },
      { name: "Conception et réalisation des voies de circulation", credits: 3, specializations: ["C"] },
      { name: "Continuum mechanics and applications", credits: 6, specializations: ["B", "D"] },
      { name: "Dam engineering", credits: 3, specializations: ["E"] },
      { name: "Decision-aid methodologies in transportation", credits: 4, specializations: ["C"] },
      { name: "Deep learning for autonomous vehicles", credits: 6, specializations: ["C"] },
      { name: "Design of precast concrete structures", credits: 3, specializations: [] },
      { name: "Dynamics of structures", credits: 4, specializations: ["D"] },
      { name: "Energy and comfort in buildings", credits: 5, specializations: ["F"] },
      { name: "Energy conversion and renewable energy", credits: 4, specializations: ["E", "F"] },
      { name: "Energy geostructures", credits: 4, specializations: ["B", "F"] },
      { name: "Engineering of existing structures", credits: 4, specializations: ["D"] },
      { name: "Fracture of materials", credits: 4, specializations: ["B"] },
      { name: "Fundamentals of traffic operations and control", credits: 4, specializations: ["C"] },
      { name: "Geotechnical earthquake engineering", credits: 3, specializations: ["B", "D"] },
      { name: "Hydraulic structures", credits: 4, specializations: ["E"] },
      { name: "Hydrologie urbaine", credits: 4, specializations: ["E"] },
      { name: "Mathematical modelling of structures", credits: 4, specializations: ["D"] },
      { name: "Nonlinear analysis of structures", credits: 4, specializations: ["D"] },
      { name: "River hydraulics and fluvial engineering", credits: 3, specializations: ["E"] },
      { name: "Seismic engineering", credits: 4, specializations: ["D"] },
      { name: "Soil mechanics", credits: 4, specializations: ["B"] },
      { name: "Urban hydraulic systems", credits: 4, specializations: ["E"] },
      { name: "Geotechnical laboratory and field testing", credits: 4, specializations: ["B"] },
      { name: "Groundwater hydrology", credits: 4, specializations: ["B", "E"] },
      { name: "Hydrology for engineers", credits: 4, specializations: ["E"] },
      { name: "Image processing for earth observation", credits: 4, specializations: ["C"] },
      { name: "Indoor air quality and ventilation", credits: 4, specializations: ["F"] },
      { name: "Introduction to urban operations research", credits: 4, specializations: ["C"] },
      { name: "Modal choice and demand management", credits: 3, specializations: ["C"] },
      { name: "Modern timber structures", credits: 4, specializations: ["D"] },
      { name: "Physics of solar energy conversion", credits: 4, specializations: ["F"] },
      { name: "Reinforced concrete structures", credits: 4, specializations: ["D"] },
      { name: "Rock mechanics", credits: 4, specializations: ["B"] },
      { name: "Slope stability", credits: 4, specializations: ["B"] },
      { name: "Steel structures II", credits: 4, specializations: ["D"] },
      { name: "Structural systems and safety", credits: 4, specializations: ["D"] },
      { name: "Sustainable building renovation", credits: 4, specializations: ["D", "F"] },
      { name: "Transport economics", credits: 3, specializations: ["C"] },
      { name: "Transportation systems engineering", credits: 4, specializations: ["C"] },
      { name: "Travel survey methods", credits: 2, specializations: ["C"] },
      { name: "Urban data science", credits: 4, specializations: ["C", "F"] },
      { name: "Water resources engineering and management", credits: 5, specializations: ["E"] },
    ],
    innovationCourses: [
      { name: "Civil engineering project 1", credits: 8 },
      { name: "Civil engineering project 2", credits: 8 },
      { name: "Projet ENAC or UE architecture", credits: 4 },
      { name: "Summer Workshop", credits: 4 },
      { name: "UE génie civil: Advanced drawing structures", credits: 4 },
    ],
    minors: [
      "Computational science and engineering",
      "Data science",
      "Energy",
      "Engineering for sustainability",
      "Imaging",
      "Integrated design, architecture and sustainability (IDEAS)",
      "Management, technology and entrepreneurship",
      "Sustainable construction",
    ],
  },
  "5fb9a7dd-f940-4494-b347-9e50a4cef25a": {
    // URB-SYS (Urban Systems)
    structure: {
      total_credits: 120,
      duration: "2 years",
      contact_email: "urbansystems.info@epfl.ch",
      website: "go.epfl.ch/master-urban-systems",
      internship_note: "The program includes a compulsory 8-week internship which can be extended to 6 months.",
    },
    components: [
      { name: "Master's Thesis", credits: 30, color: "hsl(var(--chart-1))" },
      { name: "Core Foundations", credits: 19, color: "hsl(var(--chart-2))" },
      { name: "Specialization", credits: 30, color: "hsl(var(--chart-3))" },
      { name: "Core Options", credits: 13, color: "hsl(var(--chart-4))" },
      { name: "SHS Projects", credits: 15, color: "hsl(var(--chart-5))" },
      { name: "Internship", credits: 13, color: "hsl(var(--muted))" },
    ],
    specializations: [
      { code: "A", name: "Mobility and Transportation", color: "bg-blue-500" },
      { code: "B", name: "Sustainable Transitions", color: "bg-green-500" },
      { code: "C", name: "Health and Well-being", color: "bg-purple-500" },
    ],
    coreCourses: [
      { name: "Computational systems thinking for sustainable engineering", credits: 4, specializations: [] },
      { name: "Social justice and transition in the urban context", credits: 3, specializations: [] },
      { name: "Systems approaches for urban transitions", credits: 4, specializations: [] },
      { name: "Urban digital twins", credits: 4, specializations: [] },
      { name: "Urban governance", credits: 4, specializations: [] },
    ],
    optionCourses: [
      { name: "Climate and water sensitive urban design", credits: 4, specializations: [] },
      { name: "Computational methods in urban studies", credits: 3, specializations: [] },
      { name: "Ecological contributions to cities in transformation", credits: 3, specializations: [] },
      { name: "Innovation for construction and the environment", credits: 3, specializations: [] },
      { name: "AI for urban history", credits: 4, specializations: ["B", "C"] },
      { name: "Air pollution", credits: 5, specializations: ["C"] },
      { name: "Analyse territoriale et urbaine", credits: 4, specializations: ["B"] },
      { name: "Behind/Beyond future cities", credits: 3, specializations: ["B"] },
      { name: "Building design in the circular economy", credits: 3, specializations: ["B"] },
      { name: "City and mobility", credits: 3, specializations: ["A"] },
      { name: "Comfort and architecture: sustainable strategies", credits: 3, specializations: ["C"] },
      { name: "Conception et réalisation des voies de circulation", credits: 3, specializations: ["A"] },
      { name: "Decision-aid methodologies in transportation", credits: 4, specializations: ["A"] },
      { name: "Digital epidemiology", credits: 4, specializations: ["C"] },
      { name: "Energy supply, economics, and transition", credits: 2, specializations: ["A", "B"] },
      { name: "Exploratory data analysis in environmental health", credits: 4, specializations: ["C"] },
      { name: "Fundamentals of traffic operations and control", credits: 4, specializations: ["A"] },
      { name: "Green spaces - concepts and planning approaches", credits: 4, specializations: ["A", "B", "C"] },
      { name: "Groundwater and soil remediation", credits: 4, specializations: ["C"] },
      { name: "Image processing for earth observation", credits: 4, specializations: ["A", "C"] },
      { name: "Indoor air quality and ventilation", credits: 4, specializations: ["C"] },
    ],
    minors: [],
  },
  "bc20c2b2-632e-47a7-8c0b-693ca5655254": {
    // ENV-Sc (Environmental Sciences)
    structure: {
      total_credits: 120,
      duration: "2 years",
      contact_email: "master.sie@epfl.ch",
      website: "go.epfl.ch/master-environmental-engineering",
      internship_note: "The program includes a compulsory 8-week internship which can be extended to 6 months.",
    },
    components: [
      { name: "Master's Thesis", credits: 30, color: "hsl(var(--chart-1))" },
      { name: "Core Courses", credits: 25, color: "hsl(var(--chart-2))" },
      { name: "Options", credits: 50, color: "hsl(var(--chart-3))" },
      { name: "SHS Requirements", credits: 6, color: "hsl(var(--chart-4))" },
      { name: "Internship", credits: 9, color: "hsl(var(--chart-5))" },
    ],
    specializations: [
      { code: "D", name: "Water Resources and Management (WRM)", color: "bg-blue-500" },
      { code: "E", name: "Climate Change Anticipation and Adaptation (CCAA)", color: "bg-orange-500" },
      { code: "F", name: "Environmental Sensing and Computation (ESC)", color: "bg-purple-500" },
      { code: "G", name: "Biological and Chemical Processes (BCP)", color: "bg-green-500" },
    ],
    coreCourses: [
      { name: "Atmospheric processes: from cloud to global scales", credits: 5, specializations: ["E"] },
      { name: "Sensing and spatial modeling for earth observation", credits: 5, specializations: ["F"] },
      { name: "Sustainability, climate and energy", credits: 5, specializations: [] },
      { name: "Water and wastewater treatment", credits: 5, specializations: ["G"] },
      { name: "Water resources engineering and management", credits: 5, specializations: ["D"] },
    ],
    optionCourses: [
      { name: "Air pollution", credits: 5, specializations: ["E"] },
      { name: "Applied data analysis", credits: 8, specializations: ["F"] },
      { name: "Applied ecology", credits: 4, specializations: ["E", "G"] },
      { name: "Applied wastewater engineering", credits: 3, specializations: ["D", "G"] },
      { name: "Basics of mobile robotics", credits: 4, specializations: ["F"] },
      { name: "Climate and water sensitive urban design", credits: 4, specializations: ["D", "E"] },
      { name: "Development engineering", credits: 4, specializations: [] },
      { name: "Distributed intelligent systems", credits: 5, specializations: ["F"] },
      { name: "Ecohydrological modeling", credits: 4, specializations: ["D"] },
      { name: "Ecological contributions to cities in transformation", credits: 3, specializations: ["E"] },
      { name: "Energy conversion and renewable energy", credits: 4, specializations: ["E"] },
      { name: "Environmental economics", credits: 4, specializations: [] },
      { name: "Environmental transport phenomena", credits: 5, specializations: ["F"] },
      { name: "Etudes d'impact sur l'environnement", credits: 3, specializations: ["E"] },
      { name: "Exploratory data analysis in environmental health", credits: 4, specializations: ["E", "F"] },
      { name: "Fate and behaviour of environmental contaminants", credits: 4, specializations: ["G"] },
      { name: "Global change ecology and fluvial ecosystems", credits: 4, specializations: ["D", "G"] },
      { name: "Groundwater and soil remediation", credits: 4, specializations: ["D", "G"] },
      { name: "Hydraulique fluviale et aménagement de cours d'eau", credits: 3, specializations: ["D"] },
      { name: "Hydrogeophysics", credits: 3, specializations: ["D", "G"] },
      { name: "Hydrologie urbaine", credits: 4, specializations: ["D", "E", "G"] },
      { name: "Image processing for earth observation", credits: 4, specializations: ["E", "F"] },
      { name: "Image processing I", credits: 3, specializations: ["F"] },
      { name: "Image processing II", credits: 3, specializations: ["F"] },
      { name: "Indoor air quality and ventilation", credits: 4, specializations: ["F"] },
      { name: "Irrigation and drainage engineering", credits: 4, specializations: ["D"] },
      { name: "Limnology", credits: 5, specializations: ["D", "G"] },
      { name: "Material flow analysis and resource management", credits: 4, specializations: ["G"] },
      { name: "Microbial ecology", credits: 4, specializations: ["G"] },
      { name: "Multivariate statistics in R", credits: 4, specializations: ["F", "G"] },
      { name: "Occupational and environmental health", credits: 3, specializations: ["G"] },
      { name: "Physics and hydrology of snow", credits: 4, specializations: ["D", "E"] },
      { name: "Risques hydrologiques et aménagements", credits: 3, specializations: ["D", "E"] },
    ],
    minors: ["Data science", "Energy", "Engineering for sustainability", "Imaging", "Integrated design, architecture and sustainability"],
  },
  "635c552a-b819-4c1f-ac01-7b8841c2ac8b": {
    // CHB-ENG (Chemical Engineering and Biotechnology)
    structure: {
      total_credits: 120,
      duration: "2 years",
      contact_email: "scgc@epfl.ch",
      website: "go.epfl.ch/master-chemical-engineering",
      internship_note: "Students may opt for a 30 ECTS minor instead of the industrial internship.",
    },
    components: [
      { name: "Master's Thesis", credits: 30, color: "hsl(var(--chart-1))" },
      { name: "Core Courses", credits: 18, color: "hsl(var(--chart-2))" },
      { name: "Options", credits: 42, color: "hsl(var(--chart-3))" },
      { name: "Lab & Project", credits: 12, color: "hsl(var(--chart-4))" },
      { name: "SHS Requirements", credits: 6, color: "hsl(var(--chart-5))" },
      { name: "Industrial Internship", credits: 12, color: "hsl(var(--muted))" },
    ],
    specializations: [
      { code: "A", name: "Energy and Sustainability", color: "bg-green-500" },
      { code: "B", name: "Biotechnology", color: "bg-blue-500" },
      { code: "C", name: "Materials and Food Engineering", color: "bg-orange-500" },
      { code: "S", name: "Catalysis/Sustainability Specialization", color: "bg-purple-500" },
    ],
    coreCourses: [
      { name: "Chemical engineering", credits: 4, specializations: [] },
      { name: "Diffusion and mass transfer", credits: 4, specializations: [] },
      { name: "Heterogeneous reaction engineering", credits: 4, specializations: [] },
      { name: "Management and safety", credits: 3, specializations: [] },
      { name: "Safety of chemical processes", credits: 3, specializations: [] },
    ],
    optionCourses: [
      // Theme A: Energy and sustainability
      { name: "Automated and data-driven laboratories", credits: 2, specializations: ["A", "S"] },
      { name: "Catalysis for emission control and energy processes", credits: 3, specializations: ["A"] },
      { name: "Catalysis for energy storage", credits: 3, specializations: ["A"] },
      { name: "Modeling and optimization of energy systems", credits: 4, specializations: ["A"] },
      { name: "Nanomaterials for chemical engineering application", credits: 3, specializations: ["A"] },
      { name: "Solid state chemistry and energy applications", credits: 3, specializations: ["A"] },
      { name: "Sustainable chemicals manufacture: concepts/tools", credits: 4, specializations: ["A", "S"] },
      { name: "Sustainable chemistry and engineering in industry", credits: 2, specializations: ["A", "S"] },
      { name: "Thermodynamics of energy conversion and storage", credits: 3, specializations: ["A"] },
      // Theme B: Biotechnology
      { name: "Bioprocesses and downstream processing", credits: 4, specializations: ["B"] },
      { name: "Biotechnology lab", credits: 4, specializations: ["B"] },
      { name: "Food biotechnology", credits: 3, specializations: ["B", "C"] },
      { name: "Nanobiotechnology", credits: 3, specializations: ["B"] },
      { name: "Principles and applications of systems biology", credits: 4, specializations: ["B"] },
      { name: "Selected topics in life sciences", credits: 3, specializations: ["B"] },
      { name: "Synthetic biology", credits: 4, specializations: ["B"] },
      // Theme C: Materials and food engineering
      { name: "Chemistry of food processes", credits: 3, specializations: ["C"] },
      { name: "Chimie des denrées alimentaires", credits: 3, specializations: ["C"] },
      { name: "Entrepreneurship in food and nutrition science", credits: 4, specializations: ["C"] },
      { name: "Organic electronic materials", credits: 3, specializations: ["C"] },
      { name: "Physical and chemical analyses of materials", credits: 3, specializations: ["C"] },
      { name: "Physical chemistry of polymeric materials", credits: 3, specializations: ["C"] },
      { name: "Polymer chemistry and macromolecular engineering", credits: 3, specializations: ["C"] },
      { name: "Risk management", credits: 3, specializations: ["C"] },
      // Catalysis specialization options
      { name: "Advanced nuclear magnetic resonance", credits: 3, specializations: ["S"] },
      { name: "AI for chemistry", credits: 3, specializations: ["S"] },
      { name: "Asymmetric catalysis for fine chemicals synthesis", credits: 3, specializations: ["S"] },
      { name: "Catalyst design for synthesis", credits: 2, specializations: ["S"] },
      { name: "Energy conversion by semiconductor devices", credits: 2, specializations: ["S"] },
      { name: "Machine learning for physicists", credits: 6, specializations: ["S"] },
      { name: "Optical methods in chemistry", credits: 3, specializations: ["S"] },
      // Sustainability specialization options
      { name: "Environmental Economics", credits: 4, specializations: ["S"] },
      { name: "Environmental system analysis and assessment", credits: 5, specializations: ["S"] },
      { name: "Fate and behaviour of environmental contaminants", credits: 4, specializations: ["S"] },
      { name: "Introduction to ethics and critical thinking", credits: 3, specializations: ["S"] },
      { name: "Process intensification and green chemistry", credits: 3, specializations: ["S"] },
      { name: "Science of climate change", credits: 4, specializations: ["S"] },
    ],
    minors: ["Engineering for sustainability", "Materials science and engineering", "Physics"],
  },
  "0736f75a-017e-45ed-9182-0367f49a043c": {
    // PH (Physics and Applied Physics)
    structure: {
      total_credits: 120,
      duration: "2 years",
      contact_email: "daniele.mari@epfl.ch",
      website: "go.epfl.ch/master-physics",
      internship_note: null,
    },
    components: [
      { name: "Master's Thesis", credits: 30, color: "hsl(var(--chart-1))" },
      { name: "Optional Courses", credits: 38, color: "hsl(var(--chart-2))" },
      { name: "Projects", credits: 16, color: "hsl(var(--chart-3))" },
      { name: "SHS Requirements", credits: 6, color: "hsl(var(--chart-4))" },
      { name: "Free Electives", credits: 30, color: "hsl(var(--chart-5))" },
    ],
    specializations: [
      { code: "A", name: "Applied Physics", color: "bg-blue-500" },
      { code: "B", name: "Experimental Physics", color: "bg-green-500" },
      { code: "C", name: "Theoretical Physics", color: "bg-purple-500" },
    ],
    coreCourses: [],
    optionCourses: [
      { name: "Advanced superconducting magnet technologies", credits: 4, specializations: ["A", "B"] },
      { name: "Astrophysics II: interaction of radiation with matter", credits: 4, specializations: ["A", "C"] },
      { name: "Astrophysics III: galaxy formation and evolution", credits: 4, specializations: ["A", "C"] },
      { name: "Astrophysics IV: stellar and galactic dynamics", credits: 4, specializations: ["A", "C"] },
      { name: "Astrophysics V: observational cosmology", credits: 4, specializations: ["A", "C"] },
      { name: "Attosecond radiation sources", credits: 4, specializations: ["A", "B"] },
      { name: "Biophysics: physics of biological systems", credits: 4, specializations: ["A", "C"] },
      { name: "Computational quantum physics", credits: 6, specializations: ["A", "B"] },
      { name: "Computer simulation of physical systems", credits: 4, specializations: ["A", "B"] },
      { name: "Electron microscopy: advanced methods", credits: 3, specializations: ["A", "B"] },
      { name: "Frontiers in nanosciences", credits: 4, specializations: ["A", "B"] },
      { name: "Fundamentals of biomedical imaging", credits: 4, specializations: ["A", "B"] },
      { name: "Interacting quantum matter", credits: 4, specializations: ["A", "C"] },
      { name: "Introduction to astroparticle physics", credits: 4, specializations: ["A", "C"] },
      { name: "Introduction to particle accelerators", credits: 4, specializations: ["A", "B"] },
      { name: "Machine learning for physicists", credits: 6, specializations: ["A", "B"] },
      { name: "Magnetism in materials", credits: 4, specializations: ["A", "C"] },
      { name: "Mathematical aspects of quantum physics", credits: 4, specializations: ["A", "C"] },
      { name: "Microwave engineering in physics", credits: 4, specializations: ["A", "B"] },
      { name: "Modeling and design of experiments", credits: 4, specializations: ["A", "B"] },
      { name: "Modern approaches to quantum gravity", credits: 8, specializations: ["A", "C"] },
      { name: "MRI practicals on CIBM preclinical imaging systems", credits: 4, specializations: ["A", "B"] },
      { name: "Neutron and X-ray scattering of quantum materials", credits: 4, specializations: ["A", "C"] },
      { name: "Nonlinear dynamics, chaos and complex systems", credits: 6, specializations: ["A", "B"] },
      { name: "Nonlinear optics for quantum technologies", credits: 4, specializations: ["A", "B"] },
      { name: "Nuclear fusion and plasma physics", credits: 4, specializations: ["A", "B"] },
      { name: "Nuclear interaction: from reactors to stars", credits: 4, specializations: ["A", "B"] },
      { name: "Particle detection", credits: 4, specializations: ["A", "B"] },
      { name: "Particle physics: the flavour frontiers", credits: 4, specializations: ["A", "C"] },
      { name: "Particle physics I", credits: 4, specializations: ["A", "C"] },
      { name: "Particle physics II", credits: 4, specializations: ["A", "C"] },
      { name: "Physics of life", credits: 4, specializations: ["A", "B"] },
      { name: "Physics of low-dimensional materials", credits: 4, specializations: ["A", "B"] },
      { name: "Physics of materials", credits: 4, specializations: ["A", "B"] },
      { name: "Physics of photonic semiconductor devices", credits: 4, specializations: ["A", "B"] },
      { name: "Plasma I", credits: 6, specializations: ["A", "C"] },
      { name: "Plasma II", credits: 6, specializations: ["A", "B"] },
      { name: "Quantum computing", credits: 6, specializations: ["A", "C"] },
      { name: "Quantum electrodynamics and quantum optics", credits: 6, specializations: ["A", "C"] },
      { name: "Quantum field theory I", credits: 6, specializations: ["A", "C"] },
      { name: "Quantum field theory II", credits: 6, specializations: ["A", "C"] },
      { name: "Quantum field theory III", credits: 8, specializations: ["A", "C"] },
      { name: "Quantum information theory", credits: 4, specializations: ["A", "C"] },
      { name: "Quantum optics and quantum information", credits: 6, specializations: ["A", "B"] },
      { name: "Quantum physics III", credits: 6, specializations: ["A", "C"] },
      { name: "Quantum physics IV", credits: 6, specializations: ["A", "C"] },
      { name: "Quantum transport in mesoscopic systems", credits: 4, specializations: ["A", "B"] },
      { name: "Radiation biology, protection and applications", credits: 4, specializations: ["A", "B"] },
      { name: "Radiation detection", credits: 4, specializations: ["A", "B"] },
      { name: "Relativity and cosmology I", credits: 6, specializations: ["A", "C"] },
      { name: "Relativity and cosmology II", credits: 6, specializations: ["A", "C"] },
      { name: "Selected topics in nuclear and particle physics", credits: 4, specializations: ["A", "B"] },
      { name: "Semiconductor physics and light-matter interaction", credits: 4, specializations: ["A", "B"] },
      { name: "Solid state physics III", credits: 6, specializations: ["A", "C"] },
      { name: "Solid state physics IV", credits: 4, specializations: ["A", "C"] },
      { name: "Solid state systems for quantum information", credits: 4, specializations: ["A", "B"] },
      { name: "Spintronics: basics and applications", credits: 4, specializations: ["A", "B"] },
      { name: "Statistical physics III", credits: 6, specializations: ["A", "C"] },
      { name: "Statistical physics IV", credits: 6, specializations: ["A", "C"] },
      { name: "Statistical physics of biomacromolecules", credits: 4, specializations: ["A", "C"] },
      { name: "Statistical physics of computation", credits: 4, specializations: ["A", "C"] },
      { name: "Statistical physics: theory of phase transitions", credits: 4, specializations: ["A", "C"] },
      { name: "The standard model", credits: 8, specializations: ["A", "C"] },
      { name: "Topics in biophysics and physical biology", credits: 3, specializations: ["A", "B"] },
    ],
    innovationCourses: [
      { name: "Project in Astrophysics, particles, or high energy physics", credits: 8, specializations: [] },
      { name: "Project in Applied/Experimental Physics", credits: 8, specializations: [] },
    ],
    minors: [],
  },
  "3d6ebdf3-45ba-479f-a5eb-1fd80232027e": {
    // MA (Applied Mathematics)
    structure: {
      total_credits: 120,
      duration: "2 years",
      contact_email: "sma@epfl.ch",
      website: "go.epfl.ch/master-applied-mathematics",
      internship_note: "Students opting for a minor in engineering may shorten their industrial internship.",
    },
    components: [
      { name: "Master's Thesis", credits: 30, color: "hsl(var(--chart-1))" },
      { name: "Industrial Internship", credits: 30, color: "hsl(var(--chart-2))" },
      { name: "Optional Courses", credits: 40, color: "hsl(var(--chart-3))" },
      { name: "Semester Project", credits: 10, color: "hsl(var(--chart-4))" },
      { name: "SHS Project", credits: 6, color: "hsl(var(--chart-5))" },
      { name: "Engineering Courses", credits: 4, color: "hsl(var(--muted))" },
    ],
    specializations: [
      { code: "AG", name: "Algebra and Geometry", color: "bg-purple-500" },
      { code: "AD", name: "Algorithmic and Discrete Mathematics", color: "bg-blue-500" },
      { code: "AN", name: "Analysis", color: "bg-green-500" },
      { code: "NA", name: "Numerical Analysis", color: "bg-orange-500" },
      { code: "PS", name: "Probability and Statistics", color: "bg-red-500" },
    ],
    coreCourses: [],
    optionCourses: [
      // Algebra and Geometry track
      { name: "Algebra and geometry", credits: 5, specializations: ["AG"] },
      { name: "Abstract analysis on groups", credits: 5, specializations: ["AG"] },
      { name: "Advanced analytic number theory", credits: 5, specializations: ["AG"] },
      { name: "Algebraic geometry II - Schemes and sheaves", credits: 10, specializations: ["AG"] },
      { name: "Algebraic geometry III - Selected topics", credits: 5, specializations: ["AG"] },
      { name: "Complex manifolds", credits: 5, specializations: ["AG"] },
      { name: "Differential geometry IV - General relativity", credits: 5, specializations: ["AG"] },
      { name: "Ergodic theory", credits: 5, specializations: ["AG", "AN"] },
      { name: "Géométries euclidienne et hyperbolique", credits: 5, specializations: ["AG"] },
      { name: "Number theory - Modular forms", credits: 5, specializations: ["AG"] },
      { name: "Number theory - Selected topics", credits: 5, specializations: ["AG"] },
      { name: "Number theory - Cryptography", credits: 5, specializations: ["AG", "AD"] },
      { name: "Representation theory III - Quantum groups", credits: 5, specializations: ["AG"] },
      { name: "Riemann surfaces", credits: 5, specializations: ["AG", "AN"] },
      { name: "Student seminar in pure mathematics", credits: 5, specializations: ["AG"] },
      { name: "Topology IV.a - Algebraic K-theory", credits: 5, specializations: ["AG"] },
      { name: "Topology IV.b - Cohomology rings", credits: 5, specializations: ["AG"] },
      { name: "Topology IV.b - Homotopy theory", credits: 5, specializations: ["AG"] },
      { name: "Topology V.a - Homotopical algebra", credits: 5, specializations: ["AG"] },
    ],
    transversalCourses: [
      // Approved engineering courses (sample)
      { name: "Applied biomedical signal processing", credits: 4, specializations: [] },
      { name: "Applied data analysis", credits: 4, specializations: [] },
      { name: "Data visualization", credits: 4, specializations: [] },
      { name: "Deep learning", credits: 4, specializations: [] },
      { name: "Information security and privacy", credits: 4, specializations: [] },
      { name: "Information theory and coding", credits: 4, specializations: [] },
      { name: "Investments", credits: 4, specializations: [] },
      { name: "Mathematics of data", credits: 4, specializations: [] },
      { name: "Optimization for machine learning", credits: 4, specializations: [] },
      { name: "Quantitative risk management", credits: 4, specializations: [] },
      { name: "Relativity and cosmology", credits: 4, specializations: [] },
      { name: "Signal processing", credits: 4, specializations: [] },
      { name: "Statistical signal and data processing through applications", credits: 4, specializations: [] },
    ],
    minors: [],
  },
  "d2b049ad-d744-47b1-924f-578491b87f64": {
    // RO (Robotics)
    structure: {
      total_credits: 120,
      duration: "2 years",
      contact_email: "smt@epfl.ch",
      website: "go.epfl.ch/master-robotics",
      internship_note: "The program includes a compulsory industrial internship with a minimal duration of 8 weeks.",
    },
    components: [
      { name: "Master's Thesis", credits: 30, color: "hsl(var(--chart-1))" },
      { name: "Compulsory Courses", credits: 15, color: "hsl(var(--chart-2))" },
      { name: "Orientation", credits: 17, color: "hsl(var(--chart-3))" },
      { name: "Robotics Practicals & Project I", credits: 12, color: "hsl(var(--chart-4))" },
      { name: "Optional Courses & Project II", credits: 40, color: "hsl(var(--chart-5))" },
      { name: "SHS Requirements", credits: 6, color: "hsl(var(--muted))" },
    ],
    specializations: [
      { code: "A", name: "Industrial Robotics", color: "bg-orange-500" },
      { code: "B", name: "Medical Robotics", color: "bg-blue-500" },
      { code: "C", name: "Mobile Robotics", color: "bg-green-500" },
    ],
    coreCourses: [
      { name: "Basics of mobile robotics", credits: 4, specializations: [] },
      { name: "Basics of robotics for manipulation", credits: 3, specializations: [] },
      { name: "Machine learning I", credits: 4, specializations: [] },
      { name: "Model predictive control", credits: 4, specializations: [] },
    ],
    optionCourses: [
      { name: "Advanced control systems", credits: 3, specializations: ["A", "B", "C"] },
      { name: "Advanced MEMS and microsystems", credits: 3, specializations: ["C"] },
      { name: "Aerial robotics", credits: 5, specializations: ["C"] },
      { name: "Analyse de produits et systèmes", credits: 2, specializations: ["A"] },
      { name: "Applied and industrial robotics", credits: 3, specializations: ["A"] },
      { name: "Applied data analysis", credits: 8, specializations: ["A", "B", "C"] },
      { name: "Architecture software", credits: 3, specializations: ["A", "B", "C"] },
      { name: "Basics in bioinstrumentation", credits: 4, specializations: ["B"] },
      { name: "Commande embarquée de moteurs", credits: 3, specializations: ["A"] },
      { name: "Commande non linéaire", credits: 3, specializations: ["A", "B", "C"] },
      { name: "Computational motor control", credits: 4, specializations: ["B", "C"] },
      { name: "Computer vision", credits: 6, specializations: ["A", "B", "C"] },
      { name: "Continuous improvement of manufacturing systems", credits: 5, specializations: ["A"] },
      { name: "Controlling behavior in animals and robots", credits: 5, specializations: ["A", "B", "C"] },
      { name: "Convex optimization", credits: 5, specializations: ["B", "C"] },
      { name: "Deep learning", credits: 4, specializations: ["C"] },
      { name: "Deep learning for autonomous vehicles", credits: 6, specializations: ["C"] },
      { name: "Deep learning for optical imaging", credits: 3, specializations: ["A", "B", "C"] },
      { name: "Distributed intelligent systems", credits: 5, specializations: ["C"] },
      { name: "Embedded system design", credits: 6, specializations: ["A", "B", "C"] },
      { name: "Energy supply, economics and transition", credits: 2, specializations: ["A", "B", "C"] },
      { name: "Evolutionary robotics", credits: 3, specializations: ["C"] },
      { name: "Haptic human robot interfaces", credits: 4, specializations: ["A"] },
      { name: "Image analysis and pattern recognition", credits: 4, specializations: ["B", "C"] },
      { name: "Image processing I, II", credits: 6, specializations: ["A", "B"] },
      { name: "Industrial automation", credits: 3, specializations: ["A"] },
      { name: "Intercultural presentations skills", credits: 2, specializations: ["A", "B", "C"] },
      { name: "Introduction to bioengineering", credits: 3, specializations: ["B"] },
      { name: "Learning and adaptive control for robots", credits: 4, specializations: ["C"] },
      { name: "Legged robots", credits: 4, specializations: ["C"] },
      { name: "Machine learning II", credits: 4, specializations: ["A", "B", "C"] },
      { name: "Machine learning for predictive maintenance applications", credits: 6, specializations: ["A"] },
      { name: "Machine learning programming", credits: 2, specializations: ["A", "B", "C"] },
      { name: "Management de projet et analyse de risque", credits: 4, specializations: ["A", "B", "C"] },
      { name: "Mathematics of data: from theory to computation", credits: 6, specializations: ["A", "B", "C"] },
      { name: "Mécanismes avancés pour environnements extrêmes", credits: 3, specializations: ["B", "C"] },
      { name: "Mechanical product design and development", credits: 5, specializations: ["A", "B", "C"] },
      { name: "Micro- nano robotics", credits: 3, specializations: ["A", "B", "C"] },
      { name: "Multivariable control", credits: 4, specializations: ["C"] },
      { name: "Networked control systems", credits: 3, specializations: ["C"] },
      { name: "Neural interfaces", credits: 6, specializations: ["B"] },
      { name: "Neural signals and signal processing", credits: 6, specializations: ["B"] },
      { name: "Numerical methods in biomechanics", credits: 3, specializations: ["B"] },
      { name: "Optimal decision making", credits: 4, specializations: ["A"] },
      { name: "Organic and printed electronics", credits: 2, specializations: ["B", "C"] },
      { name: "Principles of finance", credits: 5, specializations: ["A", "B", "C"] },
      { name: "Production management", credits: 5, specializations: ["A"] },
      { name: "Quantitative imaging for engineers", credits: 3, specializations: ["A", "C"] },
      { name: "Reinforcement learning", credits: 6, specializations: ["A", "B", "C"] },
      { name: "Sensor orientation", credits: 4, specializations: ["C"] },
      { name: "Sensors in medical instrumentation", credits: 3, specializations: ["B"] },
      { name: "Space mission design and operations", credits: 2, specializations: ["C"] },
      { name: "System identification", credits: 3, specializations: ["A", "B", "C"] },
      { name: "System programming for Systems-on-chip", credits: 6, specializations: ["A", "B", "C"] },
      { name: "Translational neuroengineering", credits: 6, specializations: ["B", "C"] },
    ],
    minors: [
      "Biomedical technologies",
      "Computer science",
      "Energy",
      "Engineering for sustainability",
      "Imaging",
      "Neuro-X",
      "Photonics",
      "Physics of living systems",
      "Quantum science and engineering",
      "Space technologies",
    ],
  },
  "1e727282-7560-42d8-bd5d-1145e5821169": {
    // ME (Mechanical Engineering)
    structure: {
      total_credits: 120,
      duration: "2 years",
      contact_email: "sgm@epfl.ch",
      website: "go.epfl.ch/master-mechanical-engineering",
      internship_note: "The program includes a compulsory industrial internship with a minimal duration of 8 weeks.",
    },
    components: [
      { name: "Master's Thesis", credits: 30, color: "hsl(var(--chart-1))" },
      { name: "Options", credits: 74, color: "hsl(var(--chart-2))" },
      { name: "Semester Project", credits: 10, color: "hsl(var(--chart-3))" },
      { name: "SHS Requirements", credits: 6, color: "hsl(var(--chart-4))" },
    ],
    specializations: [
      { code: "A", name: "Fluid Mechanics", color: "bg-blue-500" },
      { code: "B", name: "Automatic and Systems", color: "bg-purple-500" },
      { code: "C", name: "Design and Production", color: "bg-orange-500" },
      { code: "D", name: "Thermal Sciences", color: "bg-red-500" },
      { code: "E", name: "Mechanics of Solids and Structures", color: "bg-green-500" },
      { code: "F", name: "Biomechanics", color: "bg-pink-500" },
    ],
    coreCourses: [],
    optionCourses: [
      // Options in mechanical engineering
      { name: "Advanced control systems", credits: 3, specializations: ["B", "C", "D", "E", "F"] },
      { name: "Advanced design for sustainable future", credits: 5, specializations: ["C"] },
      { name: "Advanced energetics", credits: 5, specializations: ["D"] },
      { name: "Advanced heat transfer", credits: 3, specializations: ["D"] },
      { name: "Aerodynamics", credits: 4, specializations: ["A", "D", "E"] },
      { name: "Aéroélasticité et interaction fluide-structure", credits: 3, specializations: ["A", "D", "E"] },
      { name: "Applied mechanical design", credits: 5, specializations: ["C", "E"] },
      { name: "Biomechanics of the cardiovascular system", credits: 3, specializations: ["A", "E", "F"] },
      { name: "Biomechanics of the musculoskeletal system", credits: 5, specializations: ["E", "F"] },
      { name: "Cavitation et phénomènes d'interface", credits: 3, specializations: ["A", "D"] },
      { name: "Commande non linéaire", credits: 3, specializations: ["B", "C", "E", "F"] },
      { name: "Continuous improvement of manufacturing systems", credits: 5, specializations: ["C"] },
      { name: "Data-driven design and fabrication methods", credits: 3, specializations: ["B", "C"] },
      { name: "Dynamic finite element analysis of structures", credits: 3, specializations: ["E"] },
      { name: "Engines and fuel cells", credits: 4, specializations: ["A", "D"] },
      { name: "Heat pump systems", credits: 3, specializations: ["D"] },
      { name: "Hydraulic turbomachines", credits: 4, specializations: ["A", "D"] },
      { name: "Hydroacoustic for hydropower plants", credits: 3, specializations: ["A", "D", "F"] },
      { name: "Hydrodynamics", credits: 5, specializations: ["A", "D", "E", "F"] },
      { name: "Instability", credits: 3, specializations: ["A"] },
      { name: "Introduction to additive manufacturing", credits: 3, specializations: ["C"] },
      { name: "Introduction to nuclear engineering", credits: 2, specializations: ["D"] },
      { name: "Liquid-gas interfacial heat and mass transfer", credits: 3, specializations: ["A", "D"] },
      { name: "Mechanical product design and development", credits: 5, specializations: ["C", "E"] },
      { name: "Mechanics of slender structures", credits: 5, specializations: ["E", "F"] },
      { name: "Mechanics of soft and biological matter", credits: 4, specializations: ["E", "F"] },
      { name: "Mechanobiology: how mechanics regulate life", credits: 4, specializations: ["F"] },
      { name: "Micro/Nanomechanical devices", credits: 4, specializations: ["B", "C", "E"] },
      { name: "Micro/Nano robotics", credits: 3, specializations: ["B", "C", "E", "F"] },
      { name: "Model predictive control", credits: 4, specializations: ["B"] },
      { name: "Modeling and optimization of energy systems", credits: 4, specializations: ["B", "D"] },
      { name: "Multiagent decision-making and control", credits: 4, specializations: ["B"] },
      { name: "Multivariable control", credits: 4, specializations: ["B"] },
      { name: "Nano-scale heat transfer", credits: 4, specializations: ["D"] },
      { name: "Networked control systems", credits: 3, specializations: ["B"] },
      { name: "Numerical flow simulation", credits: 5, specializations: ["A", "D", "F"] },
      { name: "Numerical methods in biomechanics", credits: 3, specializations: ["F"] },
      { name: "Product decarbonization and life cycle analysis", credits: 4, specializations: ["C", "D"] },
      { name: "Production management", credits: 5, specializations: ["C"] },
      { name: "Projet génie mécanique II", credits: 10, specializations: ["C", "D", "E"] },
      { name: "Renewable energy", credits: 4, specializations: ["A", "D"] },
      { name: "Solar energy conversion", credits: 4, specializations: ["D"] },
      { name: "System identification", credits: 3, specializations: ["B", "C", "D", "F"] },
      { name: "Thermal power plants", credits: 3, specializations: ["D"] },
      { name: "Turbulence", credits: 5, specializations: ["A"] },
      // Options in other programs
      { name: "Advanced additive manufacturing technologies", credits: 4, specializations: ["C", "E"] },
      { name: "Advanced composites in engineering structures", credits: 3, specializations: ["E"] },
      { name: "Assembly techniques", credits: 2, specializations: ["E"] },
      { name: "Basics of mobile robotics", credits: 4, specializations: ["B"] },
      { name: "Basics of robotics for manipulation", credits: 3, specializations: ["B", "C"] },
      { name: "Biophysics: physics of biological systems", credits: 4, specializations: ["F"] },
      { name: "Biophysics: physics of the cell", credits: 3, specializations: ["F"] },
      { name: "Capteurs", credits: 5, specializations: ["B", "E"] },
      { name: "Commande embarquée de moteurs", credits: 3, specializations: ["B"] },
      { name: "Composites polymères + TP", credits: 4, specializations: ["E"] },
      { name: "Composites technology", credits: 3, specializations: ["E"] },
      { name: "Computational motor control", credits: 4, specializations: ["B", "F"] },
      { name: "Computational optical imaging", credits: 4, specializations: [] },
      { name: "Computer simulation of physical systems I", credits: 4, specializations: ["A"] },
      { name: "Continuum mechanics and applications", credits: 6, specializations: ["E"] },
      { name: "Convex optimization", credits: 5, specializations: ["B"] },
      { name: "Corrosion et protection des métaux + TP", credits: 3, specializations: ["C"] },
      { name: "Déformations des matériaux", credits: 4, specializations: ["E"] },
      { name: "Distributed intelligent systems", credits: 5, specializations: ["B"] },
      { name: "Dynamical system theory for engineers", credits: 6, specializations: ["B"] },
      { name: "Energy and comfort in buildings", credits: 5, specializations: ["D"] },
      { name: "Energy geostructures", credits: 4, specializations: ["D"] },
      { name: "Environmental transport phenomena", credits: 5, specializations: ["A"] },
      { name: "Industrial automation", credits: 3, specializations: ["B"] },
      { name: "Innovation and entrepreneurship in engineering", credits: 10, specializations: [] },
      { name: "Laser microprocessing", credits: 2, specializations: ["C"] },
      { name: "Legged robots", credits: 4, specializations: ["B"] },
      { name: "Machine learning I", credits: 4, specializations: ["B"] },
      { name: "Machine learning II", credits: 4, specializations: ["B"] },
      { name: "Machine learning for predictive maintenance applications", credits: 6, specializations: ["C"] },
      { name: "Machine learning programming", credits: 2, specializations: ["B"] },
      { name: "Materials selection", credits: 2, specializations: ["E"] },
      { name: "Multiscale modeling of solids", credits: 4, specializations: ["E"] },
      { name: "Nonlinear analysis of structures", credits: 6, specializations: ["E"] },
      { name: "Numerical approximation of PDEs", credits: 5, specializations: ["A"] },
      { name: "Physiologie par systèmes", credits: 4, specializations: ["F"] },
      { name: "Polymer science", credits: 3, specializations: ["E"] },
      { name: "Sensors in medical instrumentation", credits: 3, specializations: ["F"] },
      { name: "Surface analysis", credits: 3, specializations: ["C"] },
      { name: "Systèmes embarqués microprogrammés", credits: 4, specializations: ["B"] },
      { name: "Thermodynamics of comfort in buildings", credits: 3, specializations: ["D"] },
      { name: "Towards sustainable materials", credits: 4, specializations: ["C"] },
      { name: "Tribology", credits: 2, specializations: ["E"] },
    ],
    minors: [
      "Biomedical technologies",
      "Computational science and engineering",
      "Energy",
      "Management, technology and entrepreneurship",
      "Materials science",
      "Space technologies",
    ],
  },
  "87d4eef2-a6d1-4ac8-9fa5-da4d49c25db6": {
    // CS (Computer Science)
    structure: {
      total_credits: 120,
      duration: "2 years",
      contact_email: "sac-master@epfl.ch",
      website: "go.epfl.ch/master-computer-science",
      internship_note: "Students can choose either an industrial internship or an additional semester project.",
    },
    components: [
      { name: "Master's Thesis", credits: 30, color: "hsl(var(--chart-1))" },
      { name: "Specialization Core", credits: 25, color: "hsl(var(--chart-2))" },
      { name: "Optional Courses", credits: 30, color: "hsl(var(--chart-3))" },
      { name: "Semester Project", credits: 12, color: "hsl(var(--chart-4))" },
      { name: "SHS Requirements", credits: 6, color: "hsl(var(--chart-5))" },
      { name: "Internship/Project", credits: 17, color: "hsl(var(--muted))" },
    ],
    specializations: [
      { code: "A", name: "Computer Security", color: "bg-red-500" },
      { code: "B", name: "Data Analytics", color: "bg-blue-500" },
      { code: "C", name: "Foundations of Software", color: "bg-purple-500" },
      { code: "D", name: "Internet Computing", color: "bg-green-500" },
      { code: "E", name: "Signals, Images and Interfaces", color: "bg-orange-500" },
      { code: "F", name: "Software Systems", color: "bg-cyan-500" },
    ],
    coreCourses: [
      { name: "Advanced algorithms", credits: 6, specializations: [] },
      { name: "Applied data analysis", credits: 6, specializations: ["B", "D"] },
      { name: "Distributed algorithms", credits: 4, specializations: ["D", "F"] },
      { name: "Machine learning", credits: 7, specializations: ["B", "E"] },
      { name: "Information security and privacy", credits: 6, specializations: ["A"] },
    ],
    optionCourses: [
      // Security specialization
      { name: "Advanced computer architecture", credits: 4, specializations: ["A", "F"] },
      { name: "Advanced topics on privacy enhancing technologies", credits: 4, specializations: ["A"] },
      { name: "Applied data analysis", credits: 6, specializations: ["A", "B", "D"] },
      { name: "Computer language processing", credits: 6, specializations: ["C", "F"] },
      { name: "Cryptography and security", credits: 6, specializations: ["A"] },
      { name: "Decentralized systems engineering", credits: 6, specializations: ["A", "D", "F"] },
      { name: "Deep learning", credits: 4, specializations: ["B", "E"] },
      { name: "Foundations of software", credits: 6, specializations: ["C"] },
      { name: "Formal verification", credits: 6, specializations: ["A", "C"] },
      { name: "Functional programming", credits: 6, specializations: ["C"] },
      { name: "Information theory and coding", credits: 6, specializations: ["B", "E"] },
      { name: "Internet analytics", credits: 6, specializations: ["B", "D"] },
      { name: "Large-scale data science for real-world data", credits: 6, specializations: ["B", "D"] },
      { name: "Machine learning for behavioral data", credits: 6, specializations: ["B", "D", "E"] },
      { name: "Modern natural language processing", credits: 6, specializations: ["B", "E"] },
      { name: "Multimodal foundation models", credits: 6, specializations: ["B", "E"] },
      { name: "Network machine learning", credits: 6, specializations: ["B", "D"] },
      { name: "Operating systems", credits: 6, specializations: ["F"] },
      { name: "Optimization for machine learning", credits: 6, specializations: ["B", "E"] },
      { name: "Parallelism and concurrency", credits: 4, specializations: ["C", "F"] },
      { name: "Principles of computer systems", credits: 6, specializations: ["F"] },
      { name: "Software security", credits: 6, specializations: ["A", "F"] },
      { name: "Sublinear algorithms for big data analysis", credits: 6, specializations: ["B"] },
      { name: "System security", credits: 6, specializations: ["A", "F"] },
      { name: "TCP/IP networking", credits: 6, specializations: ["D", "F"] },
      { name: "Topics in theoretical computer science", credits: 6, specializations: ["C"] },
      // Additional courses
      { name: "Advanced compiler construction", credits: 6, specializations: ["C", "F"] },
      { name: "Advanced topics in machine learning", credits: 4, specializations: ["B", "E"] },
      { name: "Computer graphics", credits: 6, specializations: ["E"] },
      { name: "Computer vision", credits: 6, specializations: ["E"] },
      { name: "Concurrent algorithms", credits: 6, specializations: ["C", "F"] },
      { name: "Database systems", credits: 6, specializations: ["D"] },
      { name: "Digital 3D geometry processing", credits: 6, specializations: ["E"] },
      { name: "Distributed information systems", credits: 4, specializations: ["D"] },
      { name: "Human-computer interaction", credits: 4, specializations: ["E"] },
      { name: "Image and video processing", credits: 6, specializations: ["E"] },
      { name: "Image processing I", credits: 3, specializations: ["E"] },
      { name: "Image processing II", credits: 3, specializations: ["E"] },
      { name: "Information retrieval", credits: 4, specializations: ["B", "D"] },
      { name: "Introduction to intelligent systems", credits: 4, specializations: ["B"] },
      { name: "Mobile networks", credits: 4, specializations: ["D"] },
      { name: "Principles of distributed computing", credits: 4, specializations: ["C", "D", "F"] },
      { name: "Real-time embedded systems", credits: 4, specializations: ["F"] },
      { name: "Reinforcement learning", credits: 6, specializations: ["B", "E"] },
      { name: "Semester project", credits: 12, specializations: [] },
      { name: "Speech processing", credits: 4, specializations: ["E"] },
      { name: "Statistical signal and data processing", credits: 6, specializations: ["B", "E"] },
      { name: "Virtual reality", credits: 4, specializations: ["E"] },
    ],
    minors: [
      "Biomedical technologies",
      "Computational neuroscience",
      "Data science",
      "Digital humanities",
      "Energy",
      "Financial engineering",
      "Management, technology and entrepreneurship",
      "Neuro-X",
      "Quantum science and engineering",
      "Space technologies",
    ],
  },
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    const results: string[] = [];

    for (const [programId, data] of Object.entries(MASTER_STRUCTURES)) {
      // Insert structure
      const { error: structureError } = await supabase
        .from("program_structures")
        .upsert({
          program_id: programId,
          total_credits: data.structure.total_credits,
          duration: data.structure.duration,
          contact_email: data.structure.contact_email,
          website: data.structure.website,
          internship_note: data.structure.internship_note,
        }, { onConflict: "program_id" });

      if (structureError) {
        results.push(`Structure error for ${programId}: ${structureError.message}`);
        continue;
      }

      // Delete existing related data
      await supabase.from("program_specializations").delete().eq("program_id", programId);
      await supabase.from("program_credit_components").delete().eq("program_id", programId);
      await supabase.from("program_courses").delete().eq("program_id", programId);
      await supabase.from("program_minors").delete().eq("program_id", programId);

      // Insert specializations
      if (data.specializations?.length > 0) {
        const specs = data.specializations.map((s: any, i: number) => ({
          program_id: programId,
          code: s.code,
          name: s.name,
          color: s.color,
          sort_order: i,
        }));
        const { error } = await supabase.from("program_specializations").insert(specs);
        if (error) results.push(`Specializations error: ${error.message}`);
      }

      // Insert components
      if (data.components?.length > 0) {
        const comps = data.components.map((c: any, i: number) => ({
          program_id: programId,
          name: c.name,
          credits: c.credits,
          color: c.color,
          sort_order: i,
        }));
        const { error } = await supabase.from("program_credit_components").insert(comps);
        if (error) results.push(`Components error: ${error.message}`);
      }

      // Insert courses
      const allCourses = [
        ...(data.coreCourses || []).map((c: any, i: number) => ({ ...c, category: "core", sort_order: i })),
        ...(data.transversalCourses || []).map((c: any, i: number) => ({ ...c, category: "transversal", sort_order: 100 + i })),
        ...(data.optionCourses || []).map((c: any, i: number) => ({ ...c, category: "optional", sort_order: 200 + i })),
        ...(data.innovationCourses || []).map((c: any, i: number) => ({ ...c, category: "innovation", sort_order: 300 + i })),
      ];

      if (allCourses.length > 0) {
        const courses = allCourses.map((c: any) => ({
          program_id: programId,
          name: c.name,
          credits: c.credits,
          category: c.category,
          specialization_codes: c.specializations || [],
          sort_order: c.sort_order,
        }));
        const { error } = await supabase.from("program_courses").insert(courses);
        if (error) results.push(`Courses error: ${error.message}`);
      }

      // Insert minors
      if (data.minors?.length > 0) {
        const minors = data.minors.map((m: string) => ({
          program_id: programId,
          name: m,
        }));
        const { error } = await supabase.from("program_minors").insert(minors);
        if (error) results.push(`Minors error: ${error.message}`);
      }

      results.push(`✓ Seeded ${programId}`);
    }

    return new Response(JSON.stringify({ success: true, results }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
