import { ColorPalette, ThemeId } from './types';

export const THEMES: Record<ThemeId, ColorPalette> = {
  [ThemeId.QUARTZ]: {
    name: 'Quartz',
    description: 'Soft pinks and peaches with a gentle, fine grain.',
    background: '#fff0f5',
    textColor: '#5e3a43',
    blendMode: 'multiply',
    grain: {
      intensity: 0.3,
      size: 1.8,
      type: 'fractalNoise',
    },
    colors: [
      '#ffc3a0', 
      '#ffafbd', 
      '#ffdde1', 
      '#ffffff', 
      '#ff9a9e', 
    ],
  },
  [ThemeId.OCEAN]: {
    name: 'Ocean',
    description: 'Vibrant cyans with a distinct sandy texture.',
    background: '#e0f7fa',
    textColor: '#004d40',
    blendMode: 'multiply',
    grain: {
      intensity: 0.45,
      size: 1.0,
      type: 'fractalNoise',
    },
    colors: [
      '#4facfe', 
      '#00f2fe', 
      '#a8edea', 
      '#43e97b', 
      '#ffffff', 
    ],
  },
  [ThemeId.AURORA]: {
    name: 'Aurora',
    description: 'Magical night sky with soft, misty grain.',
    background: '#1a0b2e',
    textColor: '#e0d4fc',
    blendMode: 'screen',
    grain: {
      intensity: 0.4,
      size: 1.2,
      type: 'fractalNoise',
    },
    colors: [
      '#764ba2', 
      '#667eea', 
      '#43e97b', 
      '#fa709a', 
      '#2980b9', 
    ],
  },
  [ThemeId.CHILLING]: {
    name: 'Chilling',
    description: 'Warm evening haze with medium film grain.',
    background: '#2d1b2e',
    textColor: '#ffecd2',
    blendMode: 'screen',
    grain: {
      intensity: 0.5,
      size: 1.1,
      type: 'fractalNoise',
    },
    colors: [
      '#ff9a9e', 
      '#fecfef', 
      '#feada6', 
      '#f5efef', 
      '#a18cd1', 
    ],
  },
  [ThemeId.FOREST]: {
    name: 'Forest',
    description: 'Organic greens with earthy, coarse texture.',
    background: '#0f140f',
    textColor: '#dce8dc',
    blendMode: 'overlay',
    grain: {
      intensity: 0.65,
      size: 0.7, 
      type: 'turbulence',
    },
    colors: [
      '#134e5e', 
      '#71b280', 
      '#2d3436', 
      '#55efc4', 
      '#006400', 
    ],
  },
  [ThemeId.NEON]: {
    name: 'Neon',
    description: 'Digital void with sharp, high-frequency static.',
    background: '#000000',
    textColor: '#ffffff',
    blendMode: 'screen',
    grain: {
      intensity: 0.35,
      size: 2.5, 
      type: 'fractalNoise',
    },
    colors: [
      '#ff00cc', 
      '#333399', 
      '#00ff99', 
      '#00ccff', 
      '#9900cc', 
    ],
  },
  [ThemeId.GOLD]: {
    name: 'Gold',
    description: 'Luxurious shimmer with subtle texture.',
    background: '#1e1b15',
    textColor: '#f1e6b9',
    blendMode: 'soft-light',
    grain: {
      intensity: 0.3,
      size: 1.4,
      type: 'fractalNoise',
    },
    colors: [
      '#eecda3', 
      '#ef629f', 
      '#e65c00', 
      '#f9d423', 
      '#ffffff', 
    ],
  },
  [ThemeId.FLOW]: {
    name: 'Flow',
    description: 'Bright, flowing waters with crystalline grain.',
    background: '#006994',
    textColor: '#e0f7fa',
    blendMode: 'hard-light',
    grain: {
      intensity: 0.7,
      size: 0.85, 
      type: 'fractalNoise',
    },
    colors: [
      '#00bfff', 
      '#1ca9c9', 
      '#48d1cc', 
      '#87ceeb', 
      '#ffffff', 
    ],
  },
};
